version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.4
    networks:
      - app-network

  server-b:
    build:
      context: ./backend/server-b
      dockerfile: Dockerfile
    working_dir: /usr/src/server-b
    command: ["./utils/wait-for-it.sh", "rabbitmq:5672:120", "--", "npm", "start"]
    #volumes:
    #  - ./server-b:/usr/src/server-b
    ports:
      - "5672:5672"
    networks:
      - app-network
    environment:
      - RABBIT_HOST=rabbitmq
    links:
      - rabbitmq
    depends_on: 
      - rabbitmq

  server-a:
    build:
      context: ./backend/server-a
      dockerfile: Dockerfile
    working_dir: /usr/src/server-a
    command: ["./utils/wait-for-it.sh", "rabbitmq:5672:120", "--", "npm", "start"]

    #volumes:
    #  - ./server-a:/usr/src/server-a
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - RABBIT_HOST=rabbitmq
    links:
      - rabbitmq
    depends_on: 
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /usr/src/frontend
    command: ["npm", "start"]

    networks:
      - app-network
    environment:
      - API_HOST=192.168.99.100:8080
    links:
      - server-a
    depends_on: 
      - server-a
    ports:
      - "80:3000"

networks:
  app-network:
    driver: bridge